- Fixed a typo - Add the -a short option, which makes things more convenient

diff --git a/scripts/dydisnix-augment-infra.in b/scripts/dydisnix-augment-infra.in
--- a/scripts/dydisnix-augment-infra.in
+++ b/scripts/dydisnix-augment-infra.in
@@ -4,11 +4,11 @@
 
 showUsage()
 {
-    echo "Usage: $0 -i infrastructure_expr --augument augument_expr"
+    echo "Usage: $0 -i infrastructure_expr --augment augment_expr"
     echo "Options:"
     echo
     echo "-i,--infrastructure Infrastructure Nix expression which captures properties of machines in the network"
-    echo "--augument          Nix expression which auguments additional properties into the infrastructure model"
+    echo "-a,--augment        Nix expression which augments additional properties into the infrastructure model"
     echo "-h,--help           Shows the usage of this command"
 }
 
@@ -22,7 +22,7 @@ source @DISNIX_PREFIX@/share/disnix/checks
 
 # Parse valid argument options
 
-PARAMS=`getopt -n $0 -o i:h -l infrastructure:,augument:,help -- "$@"`
+PARAMS=`getopt -n $0 -o i:a:h -l infrastructure:,augment:,help -- "$@"`
 
 if [ $? != 0 ]
 then
@@ -40,8 +40,8 @@ do
 	-i|--infrastructure)
 	    infrastructureFile=`readlink -f $2`
 	    ;;
-	--augument)
-	    augumentFile=`readlink -f $2`
+	-a|--augment)
+	    augmentFile=`readlink -f $2`
 	    ;;
 	-h|--help)
 	    showUsage
@@ -56,9 +56,9 @@ done
 
 checkInfrastructureFile
 
-if [ "$augumentFile" = "" ]
+if [ "$augmentFile" = "" ]
 then
-    echo "ERROR: An augument file must be specified!" >&2
+    echo "ERROR: An augment file must be specified!" >&2
     exit 1
 fi
 
@@ -66,13 +66,13 @@ checkTmpDir
 
 # Execute operation
 
-augumentedInfrastructureFile=`mktemp -p $TMPDIR`
+augmentedInfrastructureFile=`mktemp -p $TMPDIR`
 
-cat > $augumentedInfrastructureFile <<EOF
-import @datadir@/@PACKAGE@/augument-infra.nix {
+cat > $augmentedInfrastructureFile <<EOF
+import @datadir@/@PACKAGE@/augment-infra.nix {
   infrastructure = import $infrastructureFile;
-  augumentFun = import $augumentFile;
+  augmentFun = import $augmentFile;
 }
 EOF
 
-echo $augumentedInfrastructureFile
+echo $augmentedInfrastructureFile
